version: '3.9'

networks:
  turbo-network:
    driver: bridge

services:
  proxy:
    container_name: ${PROXY_NAME}
    restart: always
    image: nginx:alpine
    env_file:
      - .env
    # command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    networks:
      - turbo-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./configs/nginx/templates:/etc/nginx/templates:rw
      - ./configs/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./configs/nginx/proxy.conf:/etc/nginx/proxy.conf
      - ./configs/nginx/security.conf:/etc/nginx/security.conf
      - ./.certs:/etc/ssl/certs
    ports:
      - ${HTTP_PORT}:80
      - ${SSL_PORT}:443

  db:
    container_name: ${DATABASE_HOST}
    image: postgres
    profiles:
      - development
    networks:
      - turbo-network
    ports:
      - 5432:5432
    volumes:
      - ./.db-data:/var/lib/postgresql/data
    environment:
      # Beware of special characters in password that can be interpreted by shell
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    restart: unless-stopped
