package handler

import (
	"fmt"
	"net/http"
	"runtime/debug"
	"sync"

	"github.com/labstack/echo/v4"
	"gorm.io/gorm"

	"github.com/theCompanyDream/id-trials/apps/backend/controller"
	_ "github.com/theCompanyDream/id-trials/apps/backend/docs" // docs is generated by Swag CLI, you

	"github.com/theCompanyDream/id-trials/apps/backend/repository"
)

// Echo instance
var (
	server     *echo.Echo
	echoOnce   sync.Once
	initDBOnce sync.Once
	db         *gorm.DB
)

func RunServer() {
	server = controller.NewServerlessEchoServer(db)
}

func Handler(w http.ResponseWriter, r *http.Request) {
	// Initialize the database, capturing errors with full stack trace.
	initDBOnce.Do(func() {
		initial_db, err := repository.ServerlessInitDB()
		if err != nil {
			http.Error(w, fmt.Sprintf("Database initialization error: %v\n%s", err, debug.Stack()), http.StatusInternalServerError)
			return
		}
		db = initial_db
	})
	echoOnce.Do(RunServer)

	// Pass the request to Echo's HTTP handler.
	server.ServeHTTP(w, r)
}
